(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={windows:new Map,z:10,settings:{sound:true}};
const apps=[{id:"files",name:"Files",icon:"▣",title:"File Manager"},{id:"terminal",name:"Terminal",icon:"⌘",title:"Terminal"},{id:"editor",name:"Editor",icon:"✎",title:"Text Editor"},{id:"calculator",name:"Calculator",icon:"＋",title:"Calculator"},{id:"monitor",name:"Monitor",icon:"◒",title:"System Monitor"},{id:"settings",name:"Settings",icon:"⚙",title:"Settings"},{id:"taskmanager",name:"Task Manager",icon:"▤",title:"Task Manager"},{id:"developer",name:"Developer",icon:"⌁",title:"Developer Mode"}];
const kernel=window.PIJUSH.kernel,kernelReady=kernel.ready;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const notify=(t,m)=>{const n=$("#notifications"),e=document.createElement("div");e.className="toast";e.innerHTML="<strong>"+esc(t)+"</strong><span>"+esc(m)+"</span>";n.append(e);setTimeout(()=>e.remove(),3500)};
kernel.bus.on("notification",({title,message})=>notify(title,message));
function renderApps(){const g=$("#app-grid");g.innerHTML=apps.map(a=>'<button class="app-card" data-open="'+a.id+'"><div class="app-icon">'+a.icon+'</div><div class="app-name">'+a.name+"</div></button>").join("");$("#dock").innerHTML=apps.slice(0,6).map(a=>'<button title="'+a.name+'" data-open="'+a.id+'">'+a.icon+"</button>").join("")+'<button title="All applications" data-action="launcher">⊞</button>';$$("[data-open]").forEach(b=>b.onclick=()=>{openApp(b.dataset.open);$("#launcher").classList.add("hidden")})}
function focus(el){state.z++;el.style.zIndex=state.z;$$(".window").forEach(w=>w.classList.remove("active"));el.classList.add("active")}
function openApp(id){const old=state.windows.get(id);if(old){old.el.style.display="flex";focus(old.el);if(old.process.state==="suspended")kernel.processes.setState(old.process.pid,"running");return}const a=apps.find(x=>x.id===id);if(!a)return;const manifest=kernel.apps.get(id)||{name:a.name,permissions:[]};const el=document.createElement("section");el.className="window active";el.dataset.app=id;el.style.left=Math.max(16,80+state.windows.size*28)+"px";el.style.top=Math.max(12,70+state.windows.size*22)+"px";el.style.zIndex=++state.z;el.innerHTML='<div class="titlebar"><span class="title">'+a.icon+" &nbsp;"+a.title+'</span><div class="win-controls"><button data-min>—</button><button data-max>□</button><button data-close>×</button></div></div><div class="window-body"></div>';$("#windows").append(el);const process=kernel.apps.get(id)?kernel.apps.launch(id):kernel.processes.spawn(a.name,"app",id);state.windows.set(id,{el,process});mount(id,$(".window-body",el));wire(el,id);focus(el);updateDock();if(manifest.permissions?.length)notify(a.name,"Permissions: "+manifest.permissions.join(", "))}
function updateDock(){$$("[data-open]").forEach(b=>b.classList.toggle("running",!!state.windows.get(b.dataset.open)))}
function wire(el,id){el.addEventListener("pointerdown",()=>focus(el));$("[data-close]",el).onclick=()=>{el.remove();const p=state.windows.get(id)?.process;if(p)kernel.processes.kill(p.pid);state.windows.delete(id);updateDock()};$("[data-min]",el).onclick=()=>{el.style.display="none";const p=state.windows.get(id)?.process;if(p)kernel.processes.setState(p.pid,"suspended")};$("[data-max]",el).onclick=()=>{if(el.dataset.maxed){Object.assign(el.style,{left:el.dataset.l,top:el.dataset.t,width:el.dataset.w,height:el.dataset.h});delete el.dataset.maxed}else{el.dataset.l=el.style.left;el.dataset.t=el.style.top;el.dataset.w=el.style.width;el.dataset.h=el.style.height;Object.assign(el.style,{left:"8px",top:"8px",width:"calc(100% - 16px)",height:"calc(100% - 16px)"});el.dataset.maxed="1"}};let d=null;$(".titlebar",el).onpointerdown=e=>{if(e.target.closest("button")||el.dataset.maxed)return;d={x:e.clientX,y:e.clientY,l:el.offsetLeft,t:el.offsetTop};e.currentTarget.setPointerCapture(e.pointerId)};$(".titlebar",el).onpointermove=e=>{if(d){el.style.left=Math.max(0,d.l+e.clientX-d.x)+"px";el.style.top=Math.max(0,d.t+e.clientY-d.y)+"px"}};$(".titlebar",el).onpointerup=()=>d=null}
function mount(id,b){({terminal,editor,files,calculator:calc,monitor,settings,taskmanager,developer}[id]||(()=>{}))(b)}
function terminal(b){b.innerHTML='<div class="terminal"><div class="terminal-output"></div><form class="terminal-form"><span>pijush@os:~$</span><input autocomplete="off"></form></div>';const out=x=>{const o=$(".terminal-output",b);o.textContent+=x+"\n";o.scrollTop=o.scrollHeight};out("PIJUSH OS Terminal v1.1");out('Type "help" for commands.');$("form",b).onsubmit=e=>{e.preventDefault();const i=$("input",b),v=i.value.trim();out("pijush@os:~$ "+v);cmd(v,out);i.value=""}}
function cmd(v,out){const[c,...a]=v.split(/\s+/);if(c==="help")out("help  clear  date  echo  pwd  ls  cat <file>  open <app>  mkdir <name>  touch <name>  ps  kill <pid>  neofetch");else if(c==="clear")$(".terminal-output").textContent="";else if(c==="date")out(new Date);else if(c==="pwd")out("/home/pijush");else if(c==="echo")out(a.join(" "));else if(c==="ls")kernel.api("terminal").fs.list().then(x=>out(x.map(y=>y[0]).join("  "))).catch(e=>out(e.message));else if(c==="cat")kernel.api("terminal").fs.read(a[0]).then(n=>out(n?.type==="file"?n.content:"cat: file not found")).catch(e=>out(e.message));else if(c==="open"){if(apps.some(x=>x.id===a[0]))openApp(a[0]);else out("open: application not found")}else if(c==="mkdir"&&a[0])kernel.api("terminal").fs.write(a[0],{type:"dir"}).then(()=>out("created "+a[0])).catch(e=>out(e.message));else if(c==="touch"&&a[0])kernel.api("terminal").fs.write(a[0],{type:"file",content:""}).then(()=>out("created "+a[0])).catch(e=>out(e.message));else if(c==="ps")out(kernel.processes.list().map(p=>p.pid+"  "+p.state+"  "+p.name).join("\n")||"No processes");else if(c==="kill"&&a[0])out(kernel.processes.kill(Number(a[0]))?"process terminated":"process not found");else if(c==="neofetch")out("PIJUSH OS\nKernel: WebKernel 1.1\nFilesystem: IndexedDB\nSecurity: Permission Manager");else if(c)out(c+": command not found")}
function editor(b){b.innerHTML='<div class="editor"><div class="editor-toolbar"><button class="btn" data-save>Save</button><button class="btn" data-load>Load notes.txt</button><span class="muted" style="margin-left:auto">Sandbox: editor</span></div><textarea spellcheck="false"></textarea></div>';const t=$("textarea",b);kernel.api("editor").fs.read("notes.txt").then(n=>t.value=n?.content||"");$("[data-load]",b).onclick=()=>kernel.api("editor").fs.read("notes.txt").then(n=>t.value=n?.content||"");$("[data-save]",b).onclick=()=>kernel.api("editor").fs.write("notes.txt",{type:"file",content:t.value}).then(()=>notify("Editor","Saved notes.txt locally."))}
function files(b){b.innerHTML='<div class="files"><aside class="sidebar"><b>Places</b><div class="muted" style="margin-top:15px;line-height:2">Desktop<br>Documents<br>Projects<br>Downloads</div></aside><div class="file-main"><div class="muted" style="margin-bottom:10px">/home/pijush</div><div id="file-list"></div></div></div>';kernel.api("files").fs.list().then(items=>$("#file-list",b).innerHTML=items.map(([n,x])=>'<div class="file-row"><span>'+(x.type==="dir"?"▣":"□")+'</span><span>'+esc(n)+"</span></div>").join(""))}
function tokenize(s){const t=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const m=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?/i);if(m){const raw=m[0];i+=raw.length;if(/[\d.]/.test(s[i]||""))throw Error("Invalid number");t.push({type:"num",v:Number(raw)});continue}if("+-*/%()".includes(s[i])){t.push({type:s[i],v:s[i++]});continue}throw Error("Unexpected character") }return t}
function calcValue(s){const t=tokenize(s);let i=0;const peek=()=>t[i]?.type;const primary=()=>{if(peek()==="num")return t[i++].v;if(peek()==="("){i++;const v=expr();if(peek()!==")")throw Error("Missing )");i++;return v}if(peek()==="-"){i++;return-primary()}if(peek()==="+"){i++;return primary()}throw Error("Expected number")};const term=()=>{let v=primary();while(peek()==="*"||peek==="/"||peek==="%"){const op=t[i++].type,r=primary();v=op==="*" ? v*r : op==="/" ? v/r : v%r}return v};const expr=()=>{let v=term();while(peek()==="+"||peek==="-"){const op=t[i++].type,r=term();v=op==="+"?v+r:v-r}return v};const v=expr();if(i!==t.length)throw Error("Unexpected token");if(!Number.isFinite(v))throw Error("Invalid result");return v}
function calc(b){b.innerHTML='<div class="calc"><input class="calc-display" value="0" readonly><div class="calc-grid">'+["C","⌫","%","÷","7","8","9","×","4","5","6","−","1","2","3","+","0",".","(",")","="].map(x=>'<button data-key="'+x+'">'+x+"</button>").join("")+"</div></div>";let e="",d=$(".calc-display",b);$$("[data-key]",b).forEach(x=>x.onclick=()=>{const k=x.dataset.key;if(k==="C")e="";else if(k==="⌫")e=e.slice(0,-1);else if(k==="="){try{e=String(calcValue(e.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-")))}catch(err){e="";notify("Calculator",err.message)}}else e+=k;d.value=e||"0"})}
function monitor(b){b.innerHTML='<div class="panel"><h2 style="margin-top:0">System Monitor</h2><p class="muted">Kernel runtime telemetry</p><div class="cards"><div class="card">Processes<div class="metric" id="m-win">0</div></div><div class="card">Storage<div class="metric" id="m-store">—</div></div><div class="card">Viewport<div class="metric" id="m-view">—</div></div></div><div class="card" style="margin-top:18px"><b>Kernel</b><p class="muted">WebKernel 1.1 · IndexedDB · permissions enabled</p></div></div>';const t=()=>{$("#m-win",b).textContent=kernel.processes.list().filter(p=>p.state==="running").length;$("#m-view",b).textContent=innerWidth+" × "+innerHeight;kernel.fs.list().then(x=>$("#m-store",b).textContent=x.length+" items")};t();const timer=setInterval(()=>{if(b.isConnected)t();else clearInterval(timer)},1000)}
function settings(b){b.innerHTML='<div class="panel"><h2 style="margin-top:0">Settings</h2><div class="settings-row"><div><b>Sound effects</b><div class="muted">Interface notification sounds</div></div><button class="switch '+(state.settings.sound?"on":"")+'" data-sound></button></div><div class="settings-row"><div><b>Reset workspace</b><div class="muted">Restore the IndexedDB virtual filesystem</div></div><button class="btn" data-reset>Reset</button></div><div class="settings-row"><div><b>Security</b><div class="muted">Permission manager active</div></div><span class="badge">Protected</span></div></div>';$("[data-sound]",b).onclick=e=>{state.settings.sound=!state.settings.sound;e.currentTarget.classList.toggle("on")};$("[data-reset]",b).onclick=()=>{if(confirm("Reset the PIJUSH OS workspace?"))kernel.fs.reset().then(()=>notify("Workspace","Local filesystem reset."))}}
function taskmanager(b){b.innerHTML='<div class="panel"><div class="panel-head"><div><h2 style="margin:0">Task Manager</h2><span class="muted">WebKernel process manager</span></div></div><div class="table-wrap"><table><thead><tr><th>PID</th><th>Application</th><th>State</th><th>Started</th><th>Action</th></tr></thead><tbody id="process-table"></tbody></table></div></div>';const render=()=>{$("#process-table",b).innerHTML=kernel.processes.list().map(p=>'<tr><td>'+p.pid+'</td><td>'+esc(p.name)+'</td><td><span class="state '+p.state+'">'+p.state+'</span></td><td>'+new Date(p.startedAt).toLocaleTimeString()+'</td><td><button class="btn" data-pid="'+p.pid+'">Kill</button></td></tr>').join("")||'<tr><td colspan="5" class="muted">No running processes</td></tr>';$$("[data-pid]",b).forEach(x=>x.onclick=()=>{kernel.processes.kill(Number(x.dataset.pid));for(const[id,w]of state.windows)if(w.process.pid===Number(x.dataset.pid)){w.el.remove();state.windows.delete(id)}render();updateDock()})};render();const off=kernel.bus.on("process:start",render);kernel.bus.on("process:update",render);kernel.bus.on("process:exit",render);b.closest(".window").addEventListener("DOMNodeRemoved",off,{once:true})}
function developer(b){b.innerHTML='<div class="panel"><h2 style="margin-top:0">Developer Mode</h2><p class="muted">Live kernel inspection and application security.</p><div class="dev-grid"><div class="card"><b>Applications</b><pre id="apps-json"></pre></div><div class="card"><b>Permissions</b><pre id="perm-json"></pre></div><div class="card"><b>Processes</b><pre id="proc-json"></pre></div><div class="card"><b>IPC / Events</b><pre id="event-log">Waiting for kernel events…</pre></div></div></div>';const render=()=>{$("#apps-json",b).textContent=JSON.stringify(kernel.apps.list(),null,2);$("#perm-json",b).textContent=JSON.stringify(Object.fromEntries(kernel.apps.list().map(a=>[a.id,kernel.permissions.list(a.id)])),null,2);$("#proc-json",b).textContent=JSON.stringify(kernel.processes.list(),null,2)};render();["process:start","process:update","process:exit","app:launch","permission:grant","permission:revoke"].forEach(e=>kernel.bus.on(e,d=>{$("#event-log",b).textContent=e+"\n"+JSON.stringify(d,null,2);render()}))}
function launcher(){$("#launcher").classList.toggle("hidden");if(!$("#launcher").classList.contains("hidden")){$("#app-search").focus();renderApps()}}
$("#desktop").addEventListener("click",e=>{const a=e.target.closest("[data-action]");if(a?.dataset.action==="launcher")launcher();if(a?.dataset.action==="notifications")notify("Notifications","No new system events.");if(a?.dataset.action==="settings")openApp("settings")});
$("#app-search").addEventListener("input",e=>$$(".app-card").forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(e.target.value.toLowerCase())));
$("#desktop").addEventListener("contextmenu",e=>{if(e.target.closest(".window,.topbar,.dock,.launcher"))return;e.preventDefault();const m=$("#context-menu");m.innerHTML='<button data-open="terminal">Open Terminal</button><button data-open="files">Open Files</button><button data-action="launcher">Applications</button>';m.style.left=e.clientX+"px";m.style.top=e.clientY+"px";m.classList.remove("hidden");$$("[data-open]",m).forEach(x=>x.onclick=()=>{openApp(x.dataset.open);m.classList.add("hidden")});$("[data-action]",m).onclick=()=>{launcher();m.classList.add("hidden")}});
document.addEventListener("click",e=>{if(!e.target.closest("#context-menu"))$("#context-menu").classList.add("hidden")});
function clock(){const d=new Date();$("#clock").textContent=d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});$("#top-status").textContent=navigator.onLine?"Online":"Offline"}
kernelReady.then(()=>{renderApps();clock();setInterval(clock,1000);setTimeout(()=>{$("#boot").classList.add("done");openApp("monitor")},700)});
window.addEventListener("online",()=>notify("Network","Connection restored."));window.addEventListener("offline",()=>notify("Network","Offline mode active."));
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
})();