(()=>{"use strict";
const DB_NAME="pijush-os",DB_VERSION=1,STORE="files";
const seed={"Desktop":{type:"dir"},"Documents":{type:"dir"},"Projects":{type:"dir"},"Downloads":{type:"dir"},"Documents/README.txt":{type:"file",content:"Welcome to PIJUSH OS.\n\nThis workspace is managed by WebKernel."},"notes.txt":{type:"file",content:"PIJUSH OS\nA browser-native operating system experiment."}};
class EventBus{constructor(){this.map=new Map()}on(t,f){if(!this.map.has(t))this.map.set(t,new Set());this.map.get(t).add(f);return()=>this.map.get(t)?.delete(f)}emit(t,d){this.map.get(t)?.forEach(f=>f(d))}}
class FileSystem{constructor(){this.db=null;this.memory=new Map();this.ready=this.init()}async init(){if(!("indexedDB"in window)){Object.entries(seed).forEach(([p,v])=>this.memory.set(p,v));return}this.db=await new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if((await this.count())===0)for(const [p,v] of Object.entries(seed))await this.write(p,v)}async count(){if(!this.db)return this.memory.size;return new Promise((res,rej)=>{const r=this.db.transaction(STORE,"readonly").objectStore(STORE).count();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async write(path,value){await this.ready;if(!this.db){this.memory.set(path,structuredClone(value));return}return new Promise((res,rej)=>{const r=this.db.transaction(STORE,"readwrite").objectStore(STORE).put(structuredClone(value),path);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}async read(path){await this.ready;if(!this.db)return this.memory.has(path)?structuredClone(this.memory.get(path)):null;return new Promise((res,rej)=>{const r=this.db.transaction(STORE,"readonly").objectStore(STORE).get(path);r.onsuccess=()=>res(r.result?structuredClone(r.result):null);r.onerror=()=>rej(r.error)})}async remove(path){await this.ready;if(!this.db){this.memory.delete(path);return}return new Promise((res,rej)=>{const r=this.db.transaction(STORE,"readwrite").objectStore(STORE).delete(path);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}async list(prefix=""){await this.ready;if(!this.db)return [...this.memory.entries()].filter(([p])=>p.startsWith(prefix));return new Promise((res,rej)=>{const out=[];const r=this.db.transaction(STORE,"readonly").objectStore(STORE).openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return res(out);if(c.key.startsWith(prefix))out.push([c.key,c.value]);c.continue()};r.onerror=()=>rej(r.error)})}async reset(){await this.ready;if(!this.db){this.memory.clear();for(const [p,v] of Object.entries(seed))this.memory.set(p,v);return}await new Promise((res,rej)=>{const r=this.db.transaction(STORE,"readwrite").objectStore(STORE).clear();r.onsuccess=res;r.onerror=()=>rej(r.error)});for(const [p,v] of Object.entries(seed))await this.write(p,v)}}
class ProcessManager{constructor(bus){this.bus=bus;this.next=100;this.processes=new Map()}spawn(name,type="app"){const p={pid:this.next++,name,type,state:"running",startedAt:Date.now()};this.processes.set(p.pid,p);this.bus.emit("process:start",p);return p}setState(pid,state){const p=this.processes.get(pid);if(!p)return false;p.state=state;this.bus.emit("process:update",p);return true}kill(pid){const p=this.processes.get(pid);if(!p)return false;p.state="terminated";p.endedAt=Date.now();this.bus.emit("process:exit",p);return true}list(){return [...this.processes.values()].map(p=>({...p}))}}
class AppManager{constructor(bus,pm){this.bus=bus;this.pm=pm;this.apps=new Map()}register(manifest){if(!manifest?.id||this.apps.has(manifest.id))throw new Error("Invalid or duplicate app");this.apps.set(manifest.id,{...manifest,installedAt:Date.now()});this.bus.emit("app:install",manifest)}uninstall(id){if(!this.apps.delete(id))return false;this.bus.emit("app:uninstall",{id});return true}list(){return [...this.apps.values()].map(a=>({...a}))}}
class WebKernel{constructor(){this.bus=new EventBus();this.fs=new FileSystem();this.processes=new ProcessManager(this.bus);this.apps=new AppManager(this.bus,this.processes);this.ready=Promise.all([this.fs.ready]).then(()=>{for(const a of [{id:"files",name:"Files",version:"1.0.0"},{id:"terminal",name:"Terminal",version:"1.0.0"},{id:"editor",name:"Editor",version:"1.0.0"},{id:"calculator",name:"Calculator",version:"1.0.0"},{id:"monitor",name:"Monitor",version:"1.0.0"},{id:"settings",name:"Settings",version:"1.0.0"}])this.apps.register(a);this.bus.emit("kernel:ready")})}}
window.PIJUSH={kernel:new WebKernel()};
})();