(()=>{"use strict";
const MAX_SNAPSHOTS=3,MAX_SNAPSHOT_BYTES=8*1024*1024;
const bytesOf=s=>typeof TextEncoder!=="undefined"?new TextEncoder().encode(s).length:unescape(encodeURIComponent(s)).length;
function validateSnapshotName(name){if(typeof name!=="string")throw Error("Snapshot name must be text");const clean=name.trim();if(!clean||clean.length>48||/[\u0000-\u001f\u007f]/.test(clean))throw Error("Use a snapshot name from 1 to 48 characters without control characters");return clean}
function makeSnapshot(name,backup,createdAt=new Date().toISOString()){
 name=validateSnapshotName(name);if(typeof backup!=="string")throw Error("Snapshot backup is invalid");
 const bytes=bytesOf(backup);if(bytes>MAX_SNAPSHOT_BYTES)throw Error("Snapshot exceeds the 8 MB limit. Export a full backup from Settings instead.");
 const id=(typeof crypto!=="undefined"&&crypto.randomUUID)?crypto.randomUUID():"snap-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,10);
 return{id,name,createdAt,bytes,backup};
}
function validateSnapshotRecord(s){if(!s||typeof s!=="object"||typeof s.id!=="string"||!/^[-a-zA-Z0-9]{8,80}$/.test(s.id))throw Error("Invalid snapshot ID");validateSnapshotName(s.name);if(typeof s.backup!=="string"||bytesOf(s.backup)>MAX_SNAPSHOT_BYTES)throw Error("Invalid snapshot backup");if(!Number.isFinite(Date.parse(s.createdAt)))throw Error("Invalid snapshot date");return true}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const formatBytes=n=>!Number.isFinite(n)?"Unavailable":n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":(n/1048576).toFixed(1)+" MB";
const diagnostics=()=>{
 if(window.PIJUSHDiagnostics)return window.PIJUSHDiagnostics;
 const entries=[];const startedAt=new Date().toISOString();
 const record=(level,message)=>{entries.push({time:new Date().toISOString(),level,message:String(message).slice(0,1200)});if(entries.length>100)entries.shift()};
 window.PIJUSHDiagnostics={entries,record,clear:()=>{entries.length=0},export:()=>JSON.stringify({product:"PIJUSH OS",generatedAt:new Date().toISOString(),sessionStartedAt:startedAt,events:entries},null,2)};
 record("info","Diagnostics initialized");
 window.addEventListener("error",e=>record("error",(e.message||"Script error")+" "+(e.filename||"")+" :"+(e.lineno||0)));
 window.addEventListener("unhandledrejection",e=>record("error","Unhandled promise rejection: "+(e.reason?.message||e.reason||"unknown")));
 window.addEventListener("online",()=>record("info","Browser reported network online"));
 window.addEventListener("offline",()=>record("warning","Browser reported network offline"));
 return window.PIJUSHDiagnostics
};
function render(root,kernel,notify){
 const log=diagnostics();
 root.innerHTML='<div class="panel sc-panel"><div class="panel-head sc-head"><div><p class="sc-eyebrow">PIJUSH OS / CONTROL PLANE</p><h2 style="margin:0">System Center</h2><p class="muted">Runtime health, recoverable snapshots, and diagnostics in one place.</p></div><button class="btn" data-refresh>Refresh</button></div><div class="sc-metrics"><div class="card"><span class="muted">Session uptime</span><div class="metric" data-uptime>—</div></div><div class="card"><span class="muted">Active processes</span><div class="metric" data-processes>—</div></div><div class="card"><span class="muted">Workspace entries</span><div class="metric" data-files>—</div></div><div class="card"><span class="muted">Storage estimate</span><div class="metric" data-storage>—</div><small class="muted" data-storage-detail>Browser-reported usage</small></div></div><div class="sc-columns"><section class="sc-section"><div class="sc-section-head"><div><h3>Snapshot Manager</h3><p class="muted">Up to 3 named snapshots, stored separately from your workspace.</p></div><span class="badge" data-snapshot-count>0 / 3</span></div><form class="sc-create"><input data-snapshot-name maxlength="48" placeholder="Snapshot name (e.g. Before update)" aria-label="Snapshot name" required><button class="btn" type="submit">Create snapshot</button></form><p class="muted sc-note">Each snapshot is limited to 8 MB. Use Settings → Protect to export a full JSON backup for larger workspaces.</p><div data-snapshot-list class="sc-snapshot-list"><p class="muted">Loading snapshots…</p></div></section><section class="sc-section"><div class="sc-section-head"><div><h3>System Diagnostics</h3><p class="muted">Errors and browser lifecycle events from this page session.</p></div><span class="badge" data-event-count>0 events</span></div><div class="sc-diagnostic-summary" data-diagnostic-summary>Checking current session…</div><div class="sc-log" data-log></div><div class="sc-actions"><button class="btn" data-export-diagnostics>Export report</button><button class="btn" data-clear-diagnostics>Clear session log</button></div></section></div><section class="sc-section sc-capabilities"><div class="sc-section-head"><div><h3>Runtime capabilities</h3><p class="muted">Reported by this browser; unsupported metrics are shown honestly.</p></div></div><div class="sc-capability-grid"><div><span class="muted">Filesystem backend</span><strong data-backend>Checking…</strong></div><div><span class="muted">CPU usage</span><strong>Not exposed by browser</strong></div><div><span class="muted">JS heap (Chromium only)</span><strong data-heap>Unavailable</strong></div><div><span class="muted">Storage persistence</span><strong data-persistence>Checking…</strong></div><div><span class="muted">Viewport</span><strong data-viewport>—</strong></div><div><span class="muted">Network</span><strong data-network>—</strong></div></div></section></div>';
 const q=s=>root.querySelector(s);
 const download=(filename,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)};
 const renderSnapshots=async()=>{try{const list=await kernel.fs.listSnapshots();q("[data-snapshot-count]").textContent=list.length+" / "+MAX_SNAPSHOTS;const host=q("[data-snapshot-list]");if(!list.length){host.innerHTML='<div class="sc-empty">No snapshots yet. Create one before making major changes.</div>';return}host.innerHTML=list.map(s=>'<article class="sc-snapshot" data-snapshot="'+escapeHTML(s.id)+'"><div class="sc-snapshot-info"><strong>'+escapeHTML(s.name)+'</strong><span class="muted">'+new Date(s.createdAt).toLocaleString()+' · '+formatBytes(s.bytes)+'</span></div><div class="sc-snapshot-actions"><button class="btn" data-snap-action="export">Export</button><button class="btn" data-snap-action="restore">Restore</button><button class="btn" data-snap-action="delete">Delete</button></div></article>').join("")}catch(e){q("[data-snapshot-list]").innerHTML='<div class="sc-empty">Snapshot storage unavailable: '+escapeHTML(e.message)+'</div>'}};
 const renderDiagnostics=()=>{const entries=log.entries.slice().reverse();const errors=entries.filter(e=>e.level==="error").length;q("[data-event-count]").textContent=entries.length+" events";q("[data-diagnostic-summary]").textContent=errors?errors+" error event"+(errors===1?"":"s")+" recorded this session":"No JavaScript errors recorded in this session";q("[data-log]").innerHTML=entries.length?entries.slice(0,12).map(e=>'<div class="sc-log-row"><span class="sc-level '+escapeHTML(e.level)+'">'+escapeHTML(e.level)+'</span><span class="sc-log-message">'+escapeHTML(e.message)+'</span><time>'+new Date(e.time).toLocaleTimeString()+'</time></div>').join(""):'<div class="sc-empty">No diagnostic events recorded.</div>'};
 const refresh=async()=>{const uptime=Math.floor((performance.now()||0)/1000);q("[data-uptime]").textContent=uptime<60?uptime+"s":Math.floor(uptime/60)+"m "+uptime%60+"s";q("[data-processes]").textContent=kernel.processes.list().filter(p=>p.state==="running").length;try{q("[data-files]").textContent=(await kernel.fs.list()).length}catch{q("[data-files]").textContent="Unavailable"}q("[data-backend]").textContent=kernel.fs.db?"IndexedDB":"Memory fallback";q("[data-viewport]").textContent=innerWidth+" × "+innerHeight;q("[data-network]").textContent=navigator.onLine?"Online":"Offline";const mem=performance.memory;if(mem&&Number.isFinite(mem.usedJSHeapSize))q("[data-heap]").textContent=formatBytes(mem.usedJSHeapSize);else q("[data-heap]").textContent="Unavailable";try{const est=await navigator.storage?.estimate?.();if(est&&Number.isFinite(est.usage)){q("[data-storage]").textContent=formatBytes(est.usage);q("[data-storage-detail]").textContent="of "+formatBytes(est.quota||0)+" browser quota"}else{q("[data-storage]").textContent="Unavailable";q("[data-storage-detail]").textContent="Browser does not expose usage"}}catch{q("[data-storage]").textContent="Unavailable"}try{const p=await navigator.storage?.persisted?.();q("[data-persistence]").textContent=p===true?"Persistent":p===false?"Best effort":"Unavailable"}catch{q("[data-persistence]").textContent="Unavailable"}renderDiagnostics();await renderSnapshots()};
 q("[data-refresh]").onclick=()=>refresh();
 q(".sc-create").onsubmit=async e=>{e.preventDefault();const input=q("[data-snapshot-name]");let name;try{name=validateSnapshotName(input.value);const existing=await kernel.fs.listSnapshots();if(existing.length>=MAX_SNAPSHOTS)throw Error("The snapshot limit is 3. Export or delete an existing snapshot first.");const backup=window.PIJUSHRecovery.createBackup(await kernel.fs.list());const snapshot=makeSnapshot(name,backup);await kernel.fs.saveSnapshot(snapshot);input.value="";notify("Snapshot created",name+" · "+formatBytes(snapshot.bytes));log.record("info","Snapshot created: "+name);await refresh()}catch(err){notify("Snapshot failed",err.message)}};
 q("[data-snapshot-list]").onclick=async e=>{const button=e.target.closest("[data-snap-action]"),card=e.target.closest("[data-snapshot]");if(!button||!card)return;try{const snap=await kernel.fs.getSnapshot(card.dataset.snapshot);if(!snap)throw Error("Snapshot no longer exists");if(button.dataset.snapAction==="export"){const parsed=window.PIJUSHRecovery.parseBackup(snap.backup);download("pijush-os-"+snap.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+".json",JSON.stringify({format:window.PIJUSHRecovery.format,version:window.PIJUSHRecovery.version,createdAt:snap.createdAt,files:parsed.files},null,2),"application/json");notify("Snapshot exported",snap.name)}else if(button.dataset.snapAction==="restore"){if(!confirm("Restore snapshot “"+snap.name+"”? This replaces all current workspace files, installed apps, settings and app data. Export a backup first if needed."))return;const parsed=window.PIJUSHRecovery.parseBackup(snap.backup);await kernel.fs.replaceAll(parsed.files);log.record("warning","Workspace restored from snapshot: "+snap.name);notify("Restore complete","Reloading PIJUSH OS…");setTimeout(()=>location.reload(),650)}else if(button.dataset.snapAction==="delete"){if(!confirm("Delete snapshot “"+snap.name+"”? This cannot be undone."))return;await kernel.fs.deleteSnapshot(snap.id);log.record("info","Snapshot deleted: "+snap.name);notify("Snapshot deleted",snap.name);await refresh()}}catch(err){notify("Snapshot action failed",err.message)}};
 q("[data-export-diagnostics]").onclick=()=>download("pijush-os-diagnostics-"+new Date().toISOString().slice(0,10)+".json",log.export(),"application/json");
 q("[data-clear-diagnostics]").onclick=()=>{if(!confirm("Clear diagnostic events from this page session?"))return;log.clear();log.record("info","Diagnostic log cleared by user");renderDiagnostics()};
 const timer=setInterval(()=>{if(root.isConnected)refresh().catch(e=>log.record("warning",e.message));else clearInterval(timer)},5000);
 refresh().catch(e=>log.record("warning","Initial refresh failed: "+e.message));
 return()=>clearInterval(timer)
}
const api={render,validateSnapshotName,makeSnapshot,validateSnapshotRecord,MAX_SNAPSHOTS,MAX_SNAPSHOT_BYTES};
if(typeof module!=="undefined"&&module.exports)module.exports=api;
if(typeof window!=="undefined"){window.PIJUSHSystemCenter=api;diagnostics()}
})();